import { montserrat, calistoga } from "./font";
import "./globals.css";

export const metadata = {
  title: "Portfólio Mariane Costa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className + " " + calistoga.variable}>
        {children}
      </body>
    </html>
  );
}
